const CONFIG = {
  name: "Quidon Roethof",
  myFace: "./quidon.jpg",
  initials: "QR",
  role: "Software Developer",
  status: "HBO Software Development, part-time",
  about: "I'm a 20-year-old developer from the Netherlands. I started with Unity at 14 and got serious about programming at 16. I like knowing what happens underneath the frameworks, so a lot of my projects go low: a CPU emulator, NES assembly, a stack-based virtual machine and a compiler that runs in the browser. I also build practical things, like an AI assistant and the internal tools I shipped during my internship at MCM Research. I finished MBO 4 Software Development in 2026 and now study HBO Software Development part-time at Bit Academy.",
  stats: [ { k: "Languages", v: "6" }, { k: "", v: "age 20" }, { k: "Internship", v: "MCM Research" } ],
  languages: [ { name: "Nederlands", level: "" }, { name: "English", level: "" } ],
  contact: [
    { label: "EMAIL",    value: "quidonroethof4@gmail.com", href: "mailto:quidonroethof4@gmail.com" },
    { label: "GITHUB",   value: "Cyd'n", href: "https://github.com/cyd-n" },
    { label: "LINKEDIN", value: "Quidon Roethof", href: "https://www.linkedin.com/in/quidon-roethof-97794a2ab/" },
    { label: "ITCH",       value: "CydnGames", href: "https://cydngames.itch.io/" },
    { label: "CV",       value: "coming soon", href: "" }
  ],
  // TODO: real names, what each one does, language, year and links
  projects: [
    { title: "V-CONSOLE",     kind: "Emulator",        stack: "C#, WinFroms,",              year: "", colors: ["#ffb547", "#b3265e"], desc: "Custom virtual game console with GPU framebuffer, RGB565 color encoding, VRAM, RAM, ROM architecture and custom CPU in C#. A complete custom computing platform.", points: [], links: { play: "", source: "" } },
    { title: "QIBYTE VM",     kind: "ByteCode",       stack: "C#", year: "", colors: ["#fb6376", "#5b1a8a"], desc: "Stack-based virtual machine with custom instruction set and bytecode. Implements Forth-like semantics with full arithmetic, stack manipulation and planned binary format.",     points: [], links: { play: "", source: "" } },
    { title: "Altair AI",         kind: "AI", stack: "",              year: "", colors: ["#3fd0d4", "#1b3a9e"], desc: "A stack-based virtual machine.Configurable AI assistant with dynamic prompt engineering, persistent settings, TTS integration and retro terminal UI. Supports multiple AI personalities and Gemini models. The whole html and css is vibe coded",                points: [], links: { play: "", source: "" } },
    { title: "Browser Compiler", kind: "Compiler",        stack: "",              year: "", colors: ["#86d27a", "#1c6b5a"], desc: "A compiler that runs in the browser.",           points: [], links: { play: "", source: "" } },
    { title: "AI Assistant",     kind: "AI tool",         stack: "",              year: "", colors: ["#c6bdff", "#3b2fc0"], desc: "A personal AI assistant.",                       points: [], links: { play: "", source: "" } }
  ],
  skills: {
    A: { label: "Programming languages", files: [
      { name: "C#",         blocks: 50, level: "Advanced",               comment: "Unity, .NET, WinForms and ASP.NET Core.", iconimg: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg"},
      { name: "Python",     blocks: 38, level: "Intermediate",           comment: "", iconimg: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg" },
      { name: "JavaScript", blocks: 38, level: "Intermediate",           comment: "Used in production at MCM Research, plus Vue and Alpine.js.", iconimg:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg" },
      { name: "PHP",        blocks: 30, level: "Junior to intermediate", comment: "Used in production at MCM Research.", iconimg:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-original.svg" },
      { name: "Rust",       blocks: 22, level: "Junior",                 comment: "Internship projects, with Tokio and Ratatui.", iconimg:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rust/rust-original.svg" },
      { name: "C++",        blocks: 14, level: "Beginner to junior",     comment: "SFML.", iconimg:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg" },
      { name: "Lua",        blocks: 30, level: "Junior to intermediate", comment: "LoveD2.", iconimg:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/lua/lua-original.svg" },
      { name: "Java",       blocks: 22, level: "junior",                 comment: "", iconimg:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg" } ] },
    B: { label: "Frameworks and libraries", files: [
      { name: ".NET",            items: [".NET", "ASP.NET Core", "WinForms"], iconimg:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/dotnetcore/dotnetcore-original.svg"  },
      { name: "Alpine.js",       items: [], iconimg:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/alpinejs/alpinejs-original.svg" },
      { name: "Vue",             items: [], iconimg:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg" },
      { name: "Chart.js",        items: [], iconimg:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/chartjs/chartjs-original.svg" },
      { name: "Node.js",         items: [], iconimg:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg" },
      { name: "Tailwind CSS",    items: [], iconimg:"https://api.iconify.design/simple-icons/tailwindcss.svg"  },
      { name: "Rust libs",       items: ["Tokio", "Ratatui"], iconimg:"https://cdn.simpleicons.org/rust"  },
      { name: "Unity",           items: [], iconimg:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/unity/unity-original.svg"  },
      { name: "Love2D",          items: [], iconimg:"https://cdn.simpleicons.org/lov"  },
      { name: "SFML",            items: [], iconimg:"https://cdn.simpleicons.org/sfml"  },
      { name: "Spectra Console", items: ["Spectra Console"] } ], iconimg:""  },
    C: { label: "Tools", files: [
      { name: "Visual Studio",            comment: "Mine favourite IDE, but it dont work on Linux(mine current OS(no I dont arch I use Debian))", iconimg: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/visualstudio/visualstudio-plain.svg" },
      { name: "VS Code",                  comment: "Cheap ripe off for Visual Studio, but can run on Linux", iconimg: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vscode/vscode-original.svg" },
      { name: "JetBrains Rider",          comment: "Pretty cool, but mostly paid", iconimg: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jetbrains/jetbrains-original.svg" },
      { name: "JetBrains IntelliJ",       comment: "insine good IDE, happly I am a student(becuase this is also paid but can get a free student account)", iconimg: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/intellij/intellij-original.svg" },
      { name: "WSL",                      comment: "Cool way to use linux while using windows", iconimg: "https://cdn.simpleicons.org/linux/FFFFFF" },
      { name: "NuGet",                    comment: "", iconimg: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nuget/nuget-original.svg" },
      { name: "GitHub",                   comment: "More down then up", iconimg: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg" },
      { name: "Git",                      comment: "Cool tool better then github", iconimg: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg" },
      { name: "Postman",                  comment: "", iconimg: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postman/postman-original.svg" },
      { name: "Npm",                      comment: "", iconimg: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/npm/npm-original-wordmark.svg" },
      { name: "Docker",                   comment: "Still learning it", iconimg: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg" },
      { name: "Cargo",                    comment: "Best package manager ever", iconimg: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rust/rust-original.svg" },
      { name: "NeoVim",                   comment: "To look like a cool hacker", iconimg: "https://cdn.simpleicons.org/neovim" },
      { name: "DBeaver",                  comment: "", iconimg: "https://cdn.simpleicons.org/dbeaver" },
      { name: "PhpMyAdmin",               comment: "", iconimg: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-original.svg" },
      { name: "MariaDB",                  comment: "", iconimg: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mariadb/mariadb-original.svg" },
      { name: "Linux",                    comment: "It works better then windows", iconimg: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg" },
      { name: "Windows",                  comment: "xp, vista, 7, 8, 10, 11", iconimg: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/windows8/windows8-original.svg" },
      { name: "Android",                  comment: "", iconimg: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/android/android-original.svg" },
      { name: "Ubuntu",                   comment: "", iconimg: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ubuntu/ubuntu-plain.svg" },
      { name: "Linux mint",               comment: "", iconimg: "https://cdn.simpleicons.org/linuxmint" }, 
      { name: "Arch Linux",               comment: "", iconimg: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/archlinux/archlinux-original.svg" },
      { name: "Debain",                   comment: "My current OS", iconimg: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/debian/debian-original.svg" }] },
    D: { label: "Concepts", files: [
      { name: "Prompt engineering",       comment: "I like coding more but can write prompts for AI", iconimg: "https://api.iconify.design/mdi/robot-outline.svg" },
      { name: "Bitwise operations",       comment: "I like it. It like logic gates", iconimg: "https://api.iconify.design/mdi/code-braces.svg" },
      { name: "Memory mapping",           comment: "", iconimg: "https://api.iconify.design/mdi/memory.svg" },
      { name: "RGB565 color encoding",    comment: "insine good IDE, happly I am a student(becuase this is also paid but can get a free student account)", iconimg: "https://api.iconify.design/mdi/palette-outline.svg" },
      { name: "Binary",                   comment: "", iconimg: "https://api.iconify.design/mdi/numeric-0-box-multiple-outline.svg" },
      { name: "Hexadecimal",              comment: "", iconimg: "https://api.iconify.design/mdi/numeric-16-box-multiple-outline.svg" },
      { name: "6502 assembly",            comment: "I can only read it not write, I understand it", iconimg: "https://api.iconify.design/mdi/cpu-64-bit.svg" },
      { name: "Design patterns",          comment: "Cool and way dcleaner then noramle code", iconimg: "https://api.iconify.design/mdi/puzzle-outline.svg" },
      { name: "MVC Framework",            comment: "", iconimg: "https://api.iconify.design/mdi/view-dashboard-outline.svg" },
      { name: "SOLID",                    comment: "Cleaner then normale code", iconimg: "https://api.iconify.design/mdi/shape-outline.svg" },
      { name: "Big-O notation",           comment: "Cool and handy to pridict how good you algorithm is", iconimg: "https://api.iconify.design/mdi/chart-line.svg" },
      { name: "Algebra",                  comment: "", iconimg: "https://api.iconify.design/mdi/math-integral-box.svg" },
      { name: "Arithmetic",               comment: "", iconimg: "https://api.iconify.design/mdi/calculator-variant-outline.svg" },
      { name: "HTTP",                     comment: "", iconimg: "https://api.iconify.design/mdi/web.svg" },
      { name: "OOP",                      comment: "", iconimg: "https://api.iconify.design/mdi/graph-outline.svg" },
      { name: "Comand Line",              comment: "", iconimg: "https://api.iconify.design/mdi/console.svg" }] },

      // CPU emulation   ·     ·    ·  OOP  ·  Linux  ·  Command Line 
  },
  experience: [
    { start: "2022", end: "2023", type: "edu", title: "MBO 1", org: "Rede", points: [] },
    { start: "2021", end: "2023", type: "work", title: "Intern", org: "Werxaam", points: [] },
    { start: "2023", end: "2024", type: "edu", title: "MBO 2 ICT Support", org: "ROC Almere Buiten", points: [] },
    { start: "2023", end: "2024", type: "work", title: "Intern", org: "Probello", points: [] },
    { start: "2024", end: "now", type: "work", title: "Super market worker", org: "Vormar Lelystad", points: [] },
    { start: "2024", end: "2026", type: "edu", title: "MBO 4 Software Development", org: "ROC Almere Buiten", points: [] },
    { start: "2025", end: "2026", type: "work", title: "Software Developer Intern", org: "MCM Research", points: [
      "Built internal tools and websites in PHP and JavaScript, plus internship projects in Rust",
      "Added features to existing codebases and fixed bugs in production",
      "Gathered requirements from clients and turned them into user stories",
      "Took part in code reviews" ] },
    { start: "2026-09", end: "present", type: "edu", title: "HBO Software Development (part-time)", org: "Bit Academy", points: [] }
  ]
};
const TYPES = { work: { label: "Work", c: "#ffb547" }, edu: { label: "Study", c: "#c6bdff" }, award: { label: "Award", c: "#34d399" }, launch: { label: "Launch", c: "#ff7eb6" } };
